Repository Year-3-Assignments/conference-management-frontend, pull requests merged in 2021-05, with the labels that each got.

#2 Feature/project structure
  .babelrc
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/App.scss
  src/actions/index.js
  src/components/sample.js
  src/index.js
  src/reducers/index.js
  src/store.js
  webpack.config.js
Labels: change project structure, good first issue

#8 Feature/navbar component
  .github/workflows/build-test.yml
  .gitignore
  assets/conference_logo.png
  assets/conference_logo_light.png
  package-lock.json
  package.json
  public/index.html
  server.js
  src/App.js
  src/App.scss
  src/components/navBar/navbar.js
  src/components/navBar/navbar.scss
  src/components/sample.js
  src/routes/pageRoutes.js
  webpack.config.js
Labels: UI component, enhancement

#10 Feature/template upload
  package-lock.json
  package.json
  src/App.js
  src/App.scss
  src/components/navBar/navbar.js
  src/components/progress/progress.js
  src/components/templateUploader/createTemplate.js
  src/components/templateUploader/createTemplate.scss
  src/firebase.config.js
  webpack.config.js
Labels: UI component, enhancement

#11 Feature/footer
  src/components/footer/footer.js
  src/components/footer/footer.scss
  src/routes/pageRoutes.js
Labels: enhancement

#15 Fix/create resource
  package-lock.json
  package.json
  src/App.js
  src/App.scss
  src/components/resourceCreator/createResource.js
  src/components/resourceCreator/createResource.scss
  src/routes/pageRoutes.js
  webpack.config.js
Labels: enhancement, good first issue

#16 Feature/user signup
  .babelrc
  package-lock.json
  package.json
  src/actions/index.js
  src/actions/userActions.js
  src/pages/SignUp/Signup.js
  src/pages/SignUp/Signup.scss
  src/reducers/index.js
  src/reducers/userReducer.js
  src/routes/pageRoutes.js
Labels: UI component, enhancement

#17 Feature/resource management
  .env
  package-lock.json
  package.json
  src/App.js
  src/App.scss
  src/actions/index.js
  src/actions/resourceActions.js
  src/actions/userActions.js
  src/components/footer/footer.js
  src/components/navBar/navbar.js
  src/components/templateUploader/createTemplate.js
  src/pages/SignUp/Signup.js
  src/pages/SignUp/Signup.scss
  src/pages/userProfile/profile.js
  src/pages/userProfile/userProfilePage.js
  src/pages/userProfile/userProfilePage.scss
  src/reducers/index.js
  src/reducers/resourceReducer.js
  src/reducers/userReducer.js
  src/routes/pageRoutes.js
  webpack.config.js
Labels: UI component, enhancement

#18 Feature/user login
  src/pages/login/login.js
  src/pages/login/login.scss
  src/routes/pageRoutes.js
Labels: UI component, enhancement

#19 Feature/workshop management
  src/actions/index.js
  src/actions/workshopActions.js
  src/reducers/index.js
  src/reducers/workshopReducer.js
  src/routes/pageRoutes.js
Labels: enhancement

#20 Feature/conference management
  src/actions/conferenceActions.js
  src/actions/index.js
  src/reducers/conferenceReducer.js
  src/reducers/index.js
Labels: enhancement

#21 Feature/login
  .env
  package-lock.json
  package.json
  src/App.scss
  src/actions/conferenceActions.js
  src/actions/resourceActions.js
  src/actions/userActions.js
  src/actions/workshopActions.js
  src/pages/login/login.js
  src/reducers/userReducer.js
  webpack.config.js
Labels: enhancement

#22 Implemented the getUser account in users' profile
  package-lock.json
  package.json
  src/actions/userActions.js
  src/pages/userProfile/profile.js
  src/pages/userProfile/userProfilePage.js
  src/reducers/userReducer.js
  src/routes/pageRoutes.js
  src/store.js
Labels: enhancement

#23 Implemented resource management for user
  package-lock.json
  package.json
  src/App.scss
  src/actions/index.js
  src/actions/resourceActions.js
  src/actions/userActions.js
  src/components/navBar/navbar.js
  src/components/resourceCreator/createResource.js
  src/components/resourceCreator/createResource.scss
  src/pages/SignUp/Signup.js
  src/pages/login/login.js
  src/pages/userProfile/profile.js
  src/pages/userProfile/userProfilePage.js
  src/pages/userProfile/userProfilePage.scss
  src/pages/userResources/resources.js
  src/pages/userResources/userResource.scss
  src/reducers/resourceReducer.js
  src/reducers/userReducer.js
  src/routes/pageRoutes.js
  webpack.config.js
Labels: UI component, enhancement
